### ISSUE TITLE
Nice, but I have the original source code of BFGR WAD tools v0.39a.

### ISSUE THREAD

**Issue by saulfabregwiivc** [libertyernie/wad-tools#1]
Hi libertyernie, I'm SaulFabre from GBAtemp.

I was wondering if you can fix some issues with original source code of BFGR WAD tools v0.39a (it was written in C, i have all of its original source code), and compile it again to Windows executables (.exe) for all.

I will attach the original executables and source code of that from BFGR:
[bfgr_wadtools_v039a.zip](https://github.com/libertyernie/wad-tools/files/6765663/bfgr_wadtools_v039a.zip)

And can you also fix that bug/issue from your CCF extractor/creator https://github.com/libertyernie/ccf-tools please?: when extracting and packing the CCF, the names of the files aren't full (ex. the file "EccoTheDolphin2_USA.SGD" found in WAD "Ecco: The Tides of Time (USA)" the program shows the file as "EccoTheDolphin2_USA." but is extracted as "EccoTheDolphin2_USA". And when I repack it with that file name the inject crashes at black screen becuase the file name is not recognized by the WAD. Can you fix it please?

Hope I receive an answer soon. Thanks libertyernie for your work! :)

saulfabreg

**Comment by libertyernie** [comment]
Thanks for the link. Does this version offer any advantages? And since I'll need to add .NET support to it anyway so I can compile it that way (since that's the build system I have to work with), is it all right to patch some things (like changing strncmp to memcmp when comparing non-text data)?

**Comment by libertyernie** [comment]
By the way, the CCF problem is apparently a Windows quirk where filenames can't end in periods and spaces. Maybe as a workaround, ccfex could export the file name as hex (00-FF) when it encounters something that can't be used, and ccfarc can detect that the filename is hex (by checking how long it is - CCF format only allows 20 characters max) and doing the conversion?

**Comment by saulfabregwiivc** [comment]
> Thanks for the link. Does this version offer any advantages? And since I'll need to add .NET support to it anyway so I can compile it that way (since that's the build system I have to work with), is it all right to patch some things (like changing strncmp to memcmp when comparing non-text data)?

I don't know about this, sorry :(

> By the way, the CCF problem is apparently a Windows quirk where filenames can't end in periods and spaces. Maybe as a workaround, ccfex could export the file name as hex (00-FF) when it encounters something that can't be used, and ccfarc can detect that the filename is hex (by checking how long it is - CCF format only allows 20 characters max) and doing the conversion?

Not sure. I'm not a specialized programmer xD
But I saw you added the fix of my problem I had with Ecco 2 WAD, but can you compile it again your ccfex.c again and put the compiled version in a new release?
Greetings 👍

**Comment by saulfabregwiivc** [comment]
Saw the new update of ccf-tools https://github.com/libertyernie/ccf-tools/releases/tag/v20210711, tried it and it works with Ecco: The Tides of Time (USA) WAD now! Thanks a lot for the fix ;)

BUT, I've tried the new version of wad-tools https://github.com/libertyernie/wad-tools/releases/tag/v20210718 based in BFGR's original code but they didn't work even when I have installed Microsoft .NET Framework 4.7.2 and put the common-key.bin file in the directory of wadunpacker.exe/wadpacker.exe. I will post this bug in this issue: https://github.com/libertyernie/wad-tools/issues/2

But with ccf-tools, it's now fixed, so i will close this issue ;)

Thanks for your great work ;)
